terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Create a JSON configuration file using a template and local variables.
variable "environment" {
  type    = string
  default = "development"
}

locals {
  db_host = var.environment == "production" ? "prod.db.example.com" : "dev.db.example.com"
}

resource "pyvider_file_content" "json_config" {
  filename = "/tmp/app_config.json"
  content = jsonencode({
    app_name = "my-terraform-app"
    version  = "1.0.0"
    debug    = var.environment != "production"
    database = {
      host = local.db_host
      port = 5432
    }
  })
}

output "json_config_hash" {
  description = "Hash of the generated JSON configuration file."
  value       = pyvider_file_content.json_config.content_hash
}

