terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  numbers = [10, 5, 8, 2, 15]
  result = provider::pyvider::sum(local.numbers) # 40
}

output "sum_example" {
  value = local.result
}

