terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Basic jq operations
locals {
  data = {
    user = { name = "Alice", age = 30 }
    items = ["one", "two", "three"]
  }

  user_name = provider::pyvider::lens_jq(local.data, ".user.name")  # "Alice"
  item_count = provider::pyvider::lens_jq(local.data, ".items | length")  # 3
  first_item = provider::pyvider::lens_jq(local.data, ".items[0]")  # "one"
}

output "basic_jq" {
  value = {
    name = local.user_name
    count = local.item_count
    first = local.first_item
  }
}

