terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Use the lens_jq data source to extract a field from a JSON object.
data "pyvider_lens_jq" "example" {
  json_input = jsonencode({
    user = {
      name  = "John Doe"
      email = "john@example.com"
    }
  })
  query = ".user.name"
}

output "extracted_name" {
  description = "The name extracted from the JSON input."
  value       = data.pyvider_lens_jq.example.result
}

