terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Create a simple directory with default permissions.
resource "pyvider_local_directory" "basic_dir" {
  path = "/tmp/pyvider_basic"
}

# Create a directory with specific permissions.
resource "pyvider_local_directory" "secure_dir" {
  path        = "/tmp/pyvider_secure"
  permissions = "0o700" # Only owner can read/write/execute.
}

output "directory_paths" {
  value = {
    basic  = pyvider_local_directory.basic_dir.path
    secure = pyvider_local_directory.secure_dir.path
  }
}

output "secure_dir_permissions" {
  value = pyvider_local_directory.secure_dir.permissions
}

