terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  provider_testmode = true
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
data "pyvider_structured_object_test" "example" {
  config_name = "dumb"
  # Configuration options here
}

#output "example_data" {
#  description = "Data from pyvider_structured_object_test"
#  value       = data.pyvider_structured_object_test.example
#}

