terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  user_data = {
    id    = 123
    name  = "Alice Johnson"
    email = "alice@example.com"
  }

  user_name  = provider::pyvider::lens_jq(local.user_data, ".name")    # "Alice Johnson"
  user_email = provider::pyvider::lens_jq(local.user_data, ".email")   # "alice@example.com"
}

output "lens_jq_example" {
  value = {
    name  = local.user_name
    email = local.user_email
  }
}

