terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  item = "apple"
  singular = provider::pyvider::pluralize(local.item, 1)  # "apple"
  plural = provider::pyvider::pluralize(local.item, 2)    # "apples"
  custom = provider::pyvider::pluralize("person", 2, "people")  # "people"
}

output "pluralize_example" {
  value = {
    singular = local.singular
    plural   = local.plural
    custom   = local.custom
  }
}

