terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  text = "HelloWorld"
  kebab = provider::pyvider::to_kebab_case(local.text)
  # "hello-world"
}

output "to_kebab_case_example" {
  value = local.kebab
}

