INHERIT: ../provide-foundry/base-mkdocs.yml
site_name: Pyvider Components
site_description: Learning and reference library for Pyvider framework components
site_author: provide.io
site_url: https://foundry.provide.io/pyvider-components/
repo_url: https://github.com/provide-io/pyvider-components
repo_name: provide-io/pyvider-components
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2017 - 2025 Provide
dev_addr: 127.0.0.1:8004
docs_dir: docs
theme:
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
- Overview: index.md
- Collections:
    Functions:
      contains: functions/contains.md
      length: functions/length.md
      lookup: functions/lookup.md
- Lens:
    Data Sources:
      lens_jq: data-sources/pyvider_lens_jq.md
    Functions:
      lens_jq: functions/lens_jq.md
- Math:
    Functions:
      add: functions/add.md
      divide: functions/divide.md
      max: functions/max.md
      min: functions/min.md
      multiply: functions/multiply.md
      round: functions/round.md
      subtract: functions/subtract.md
      sum: functions/sum.md
- String Utilities:
    Functions:
      format: functions/format.md
      format_size: functions/format_size.md
      join: functions/join.md
      lower: functions/lower.md
      pluralize: functions/pluralize.md
      replace: functions/replace.md
      split: functions/split.md
      to_camel_case: functions/to_camel_case.md
      to_kebab_case: functions/to_kebab_case.md
      to_snake_case: functions/to_snake_case.md
      truncate: functions/truncate.md
      upper: functions/upper.md
- Type Conversion:
    Functions:
      tostring: functions/tostring.md
- Utilities:
    Resources:
      file_content: resources/pyvider_file_content.md
      local_directory: resources/pyvider_local_directory.md
      timed_token: resources/pyvider_timed_token.md
    Data Sources:
      env_variables: data-sources/pyvider_env_variables.md
      file_info: data-sources/pyvider_file_info.md
      http_api: data-sources/pyvider_http_api.md
      provider_config_reader: data-sources/pyvider_provider_config_reader.md
- Test Mode:
    Resources:
      private_state_verifier: resources/pyvider_private_state_verifier.md
      warning_example: resources/pyvider_warning_example.md
    Data Sources:
      mixed_map_test: data-sources/pyvider_mixed_map_test.md
      nested_data_processor: data-sources/pyvider_nested_data_processor.md
      nested_resource_test: data-sources/pyvider_nested_resource_test.md
      simple_map_test: data-sources/pyvider_simple_map_test.md
      structured_object_test: data-sources/pyvider_structured_object_test.md
