[project]
name = "pyvider-components"
dynamic = ["version"]
description = "Standard Components for the Pyvider Framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "provide-foundation",
    "pyvider-rpcplugin",
    "httpx>=0.28.1",
    "jq>=1.9.1",
    "jinja2>=3.1.6",
    "pyvider-cty>=0.0.113",
    "pyvider>=0.0.0.post0",
    "plating",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.setuptools.package-data]
"*" = ["*.plating/**/*"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "provide-testkit[grpc-dev,profiling,build]",
]

[tool.uv.sources]
provide-foundation = { workspace = true }
provide-testkit = { workspace = true }
pyvider = { workspace = true }
pyvider-cty = { workspace = true }
pyvider-rpcplugin = { workspace = true }
plating = { workspace = true }
