terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  text = "hello world"
  replaced = provider::pyvider::replace(local.text, "world", "earth")
  # "hello earth"
}

output "replace_example" {
  value = local.replaced
}

