terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
data "pyvider_structured_object_test" "with_metadata" {
  config_name = "production-config"

  metadata = {
    environment = "production"
    region      = "us-west-2"
    owner       = "platform-team"
  }
}

output "settings" {
  description = "Processed settings from metadata"
  value       = data.pyvider_structured_object_test.with_metadata.generated_config.settings
}

output "config_hash" {
  description = "Hash of the configuration name"
  value       = data.pyvider_structured_object_test.with_metadata.summary.config_hash
}

