terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
data "pyvider_http_api" "example" {
  # Configuration options here
}

output "example_data" {
  description = "Data from pyvider_http_api"
  value       = data.pyvider_http_api.example
}

