terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
data "pyvider_structured_object_test" "basic" {
  config_name = "my-config"
}

output "generated_config" {
  description = "Generated configuration object with nested attributes"
  value       = data.pyvider_structured_object_test.basic.generated_config
}

output "summary" {
  description = "Summary information with nested details"
  value       = data.pyvider_structured_object_test.basic.summary
}

