terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  shout = provider::pyvider::upper("hello world") # "HELLO WORLD"
}

output "upper_example" {
  value = local.shout
}

