terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  username = provider::pyvider::lower("ADMIN@EXAMPLE.COM") # "admin@example.com"
}

output "lower_example" {
  value = local.username
}

