terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Verify encryption of private state
resource "pyvider_private_state_verifier" "test" {
  input_value = "sensitive-data"
}

output "verification" {
  value = {
    verified      = pyvider_private_state_verifier.test.verification_successful
    hash_length   = pyvider_private_state_verifier.test.output_hash_length
    is_encrypted  = pyvider_private_state_verifier.test.state_is_encrypted
  }
}

