terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  numbers = [1, 2, 3, 4, 5]
  length_result = provider::pyvider::length(local.numbers) # 5
}

output "length_example" {
  value = local.length_result
}

