terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  text = "HelloWorld"
  snake = provider::pyvider::to_snake_case(local.text)
  # "hello_world"
}

output "to_snake_case_example" {
  value = local.snake
}

