terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Basic string manipulation
locals {
  text = "Hello World"

  uppercase = provider::pyvider::upper(local.text)  # "HELLO WORLD"
  lowercase = provider::pyvider::lower(local.text)  # "hello world"
  formatted = provider::pyvider::format("Name: {}", ["Alice"])  # "Name: Alice"
}

output "basic_strings" {
  value = {
    upper = local.uppercase
    lower = local.lowercase
    formatted = local.formatted
  }
}

