terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  csv_data = "apple,banana,cherry"
  split_by_comma = provider::pyvider::split(local.csv_data, ",")
  # ["apple", "banana", "cherry"]
}

output "split_example" {
  value = local.split_by_comma
}

