terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Make a simple GET request to a public API.
data "pyvider_http_api" "example" {
  url = "https://httpbin.org/get"
  headers = {
    "Accept" = "application/json"
  }
}

output "api_response_status" {
  description = "The HTTP status code of the API response."
  value       = data.pyvider_http_api.example.status_code
}

output "api_response_body_preview" {
  description = "A preview of the response body."
  value       = substr(data.pyvider_http_api.example.response_body, 0, 100)
}

