terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  words = ["apple", "banana", "cherry"]
  joined = provider::pyvider::join(local.words, ", ")
  # "apple, banana, cherry"
}

output "join_example" {
  value = local.joined
}

