terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
# Generate a timed token
resource "pyvider_timed_token" "example" {
  prefix       = "demo"
  length       = 32
  duration_sec = 3600  # 1 hour
}

output "token_info" {
  value = {
    token_id   = pyvider_timed_token.example.id
    expires_at = pyvider_timed_token.example.expires_at
  }
  sensitive = true
}

