terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
locals {
  to_int = provider::pyvider::round(3.7, 0)         # 4
  to_decimal = provider::pyvider::round(3.14159, 2) # 3.14
}

output "round_example" {
  value = {
    to_int     = local.to_int
    to_decimal = local.to_decimal
  }
}

