terraform {
  required_providers {
    pyvider = {
      source  = "local/providers/pyvider"
      version = ">= 0.0.5"
    }
  }
}

provider "pyvider" {
  # Provider configuration
  # Add your configuration options here
}

# Generated by Plating - Executable Example
data "pyvider_simple_map_test" "empty" {
  # No input_data provided - will use empty map
}

output "empty_result" {
  description = "Result when no input data is provided"
  value       = data.pyvider_simple_map_test.empty.processed_data
}

